#!/usr/bin/env bash
# Renders Terraform outputs into ansible/group_vars/terraform.yml so the
# EC2-agent JCasC configuration always reflects the currently-applied
# infrastructure. Run this before every ansible-playbook invocation.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="$SCRIPT_DIR/../terraform"
OUT_FILE="$SCRIPT_DIR/../ansible/group_vars/all/terraform.yml"

cd "$TF_DIR"
OUTPUTS_JSON=$(terraform output -json)

{
  echo "---"
  echo "# Auto-generated by scripts/render-tfvars.sh - do not edit by hand."
  python3 - "$OUTPUTS_JSON" "$TF_DIR" <<'PYEOF'
import json, sys
data = json.loads(sys.argv[1])
import os
tf_dir = os.path.abspath(sys.argv[2]) if len(sys.argv) > 2 else "."
for key, obj in data.items():
    value = obj["value"]
    if key == "jenkins_agent_private_key_path":
        value = os.path.relpath(os.path.join(tf_dir, value), os.path.join(tf_dir, "..", "ansible"))
    print(f"tf_{key}: {json.dumps(value)}")
PYEOF
} > "$OUT_FILE"

echo "Wrote $OUT_FILE"
