apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streamingapp.fullname" . }}-admin
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  replicas: {{ .Values.services.admin.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "streamingapp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: admin
  template:
    metadata:
      labels:
        {{- include "streamingapp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: admin
    spec:
      containers:
        - name: admin
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.services.admin.image }}:{{ .Values.imageTags.admin | default .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.services.admin.port }}
          env:
            - name: PORT
              value: {{ .Values.services.admin.port | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "streamingapp.fullname" . }}-config
            - secretRef:
                name: {{ include "streamingapp.fullname" . }}-secret
          readinessProbe:
            httpGet:
              path: {{ .Values.services.admin.healthPath }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.services.admin.healthPath }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            {{- toYaml .Values.services.admin.resources | nindent 12 }}
