apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamingapp.fullname" . }}-auth
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.auth.port }}
      targetPort: http
  selector:
    {{- include "streamingapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth
