apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streamingapp.fullname" . }}-frontend
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.services.frontend.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "streamingapp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "streamingapp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.services.frontend.image }}:{{ .Values.imageTags.frontend | default .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.services.frontend.port }}
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/env-config.js
              subPath: env-config.js
          readinessProbe:
            httpGet:
              path: {{ .Values.services.frontend.healthPath }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.services.frontend.healthPath }}
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.services.frontend.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "streamingapp.fullname" . }}-frontend-config
