{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "streamingapp.fullname" . }}-frontend
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api/streaming
            pathType: Prefix
            backend:
              service:
                name: {{ include "streamingapp.fullname" . }}-streaming
                port:
                  name: http
          - path: /api/admin
            pathType: Prefix
            backend:
              service:
                name: {{ include "streamingapp.fullname" . }}-admin
                port:
                  name: http
          - path: /api/chat
            pathType: Prefix
            backend:
              service:
                name: {{ include "streamingapp.fullname" . }}-chat
                port:
                  name: http
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: {{ include "streamingapp.fullname" . }}-chat
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "streamingapp.fullname" . }}-frontend
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "streamingapp.fullname" . }}-auth
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api/auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "streamingapp.fullname" . }}-auth
                port:
                  name: http
{{- end }}
