apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "streamingapp.fullname" . }}-streaming
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: streaming
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.awsAccountId }}:role/{{ .Values.global.clusterName }}-streaming-irsa
